### ISSUE TITLE
"A JavaScript error occured in the browser process"

### ISSUE THREAD

**Issue by hiroshi** [pastak/gyazo-menubar#1]
- Download the zip from https://www.dropbox.com/s/ccx705tu9hvh5yf/Gyazo-Menubar.app.zip?dl=1
- extract Gyazo-Menubar.app from the zip
- Open the app

[![Gyazo](https://i.gyazo.com/6e440b2a764129a377214330a670212e.png)](https://gyazo.com/6e440b2a764129a377214330a670212e)

OS X 10.10.3

**Comment by pastak** [comment]
@hiroshi thank you for your report. I re-build and upload it. plz check it!

**Comment by hiroshi** [comment]
it works. thanks.
